[package]
name = "leetcode-daily-2408"
version = "0.1.0"
edition = "2021"

[[bin]]
name="240801"
path="./240801.rs"

[[bin]]
name="240802"
path="./240802.rs"

[[bin]]
name="240803"
path="./240803.rs"

[[bin]]
name="240804_weekly_contest_409"
path="./240804_weekly_contest_409.rs"